# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatApp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatApp.proto\"(\n\x14\x43reateAccountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\">\n\x15\x43reateAccountResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x08\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\"*\n\x13ListAccountsRequest\x12\x13\n\x0blistAccount\x18\x01 \x01(\t\"@\n\x14ListAccountsResponse\x12(\n\tusernames\x18\x01 \x03(\x0b\x32\x15.CreateAccountRequest\"F\n\x12SendMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x66roUser\x18\x02 \x01(\t\x12\x0e\n\x06toUser\x18\x03 \x01(\t\"<\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\"#\n\x0e\x44\x65liverRequest\x12\x11\n\trecipient\x18\x01 \x01(\t\"#\n\x0f\x44\x65liverResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"(\n\x14\x44\x65leteAccountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"7\n\x15\x44\x65leteAccountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc0\x02\n\x07\x43hatApp\x12@\n\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponse\"\x00\x12=\n\x0cListAccounts\x12\x14.ListAccountsRequest\x1a\x15.ListAccountsResponse\"\x00\x12:\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\"\x00\x12\x36\n\x0f\x44\x65liverMessages\x12\x0f.DeliverRequest\x1a\x10.DeliverResponse\"\x00\x12@\n\rDeleteAccount\x12\x15.DeleteAccountRequest\x1a\x16.DeleteAccountResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatApp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEACCOUNTREQUEST._serialized_start=17
  _CREATEACCOUNTREQUEST._serialized_end=57
  _CREATEACCOUNTRESPONSE._serialized_start=59
  _CREATEACCOUNTRESPONSE._serialized_end=121
  _LISTACCOUNTSREQUEST._serialized_start=123
  _LISTACCOUNTSREQUEST._serialized_end=165
  _LISTACCOUNTSRESPONSE._serialized_start=167
  _LISTACCOUNTSRESPONSE._serialized_end=231
  _SENDMESSAGEREQUEST._serialized_start=233
  _SENDMESSAGEREQUEST._serialized_end=303
  _SENDMESSAGERESPONSE._serialized_start=305
  _SENDMESSAGERESPONSE._serialized_end=365
  _DELIVERREQUEST._serialized_start=367
  _DELIVERREQUEST._serialized_end=402
  _DELIVERRESPONSE._serialized_start=404
  _DELIVERRESPONSE._serialized_end=439
  _DELETEACCOUNTREQUEST._serialized_start=441
  _DELETEACCOUNTREQUEST._serialized_end=481
  _DELETEACCOUNTRESPONSE._serialized_start=483
  _DELETEACCOUNTRESPONSE._serialized_end=538
  _CHATAPP._serialized_start=541
  _CHATAPP._serialized_end=861
# @@protoc_insertion_point(module_scope)
